org.gradle.jvmargs=-Xmx768m -XX:MaxMetaspaceSize=256m -XX:ReservedCodeCacheSize=96m -XX:+UseG1GC
kotlin.daemon.jvmargs=-Xmx512m -XX:MaxMetaspaceSize=192m
org.gradle.parallel=false
org.gradle.daemon=true
android.useAndroidX=true
# This newDsl flag was added by the Flutter template
android.newDsl=false
# This builtInKotlin flag was added by the Flutter template
android.builtInKotlin=false
